version: '3.3'
services:
    it-training-db:
        container_name: it-trainig-mysql
        image: mysql:5.7
        restart: always
        environment:
            - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
            - 'MYSQL_DATABASE="${DB_NAME}'
            - 'MYSQL_USER=${DB_USER}'
            - 'MYSQL_PASSWORD=${DB_PASSWORD}'
        ports:
            - '3306:3306'
        volumes:
            - it_training_db_data:/var/lib/mysql
        networks:
            - it_training_back
    

    phpmyadmin:
        container_name: myadmin
        depends_on:
            - it-training-db
        restart: always
        networks: 
            - it_training_back
        links:
            - 'it-training-db:db'
        ports:
            - '8091:80'
        image: phpmyadmin


    formation-rest-api:
      container_name: formation-rest-api
      image: sadofrazer/ittraining_api_formation:1.0
      restart: always
      depends_on:
            - it-training-db
      ports:
            - '${FORMATION_API_PORT}:8080'
      environment:
            - 'DB_USER=${DB_USER}'
            - 'DB_PASSWORD=${DB_PASSWORD}'
            - 'DB_NAME=${DB_NAME}'
            - 'DB_HOST=it-training-db'
            - 'DB_PORT=3306'
      networks:
            - it_training_back
            - it_training_front
    

    utilisateur-rest-api:
      container_name: utilisateur-rest-api
      image: sadofrazer/ittraining_api_utilisateur:1.0
      restart: always
      depends_on:
            - it-training-db
      ports:
            - "${UTILISATEUR_API_PORT}:8080"
      environment:
            - 'DB_USER=${DB_USER}'
            - 'DB_PASSWORD=${DB_PASSWORD}'
            - 'DB_NAME=${DB_NAME}'
            - 'DB_HOST=it-training-db'
            - 'DB_PORT=3306'
      networks:
            - it_training_back
            - it_training_front


    it-training-webapp:
      container_name: angular-webapp
      image: sadofrazer/ittraining_webapp:1.0
      restart: always
      depends_on:
            - utilisateur-rest-api
            - formation-rest-api
      ports:
            - '${WEBAPP_PORT}:80'
      environment:
            - 'FORMATION_API_HOST=formation-rest-api'
            - 'UTILISATEUR_API_HOST=utilisateur-rest-api'
      networks:
            - it_training_front

volumes:
    it_training_db_data:

networks:
    it_training_back:
      driver: bridge
      name: it_training_back
    it_training_front:
      driver: bridge
      name: it_training_front